name: dart_hetimanet
description: A starting point for Dart libraries or applications.
version: 0.0.1
#author: <your name> <email@example.com>
#homepage: https://www.example.com
#dependencies:
#  lib_name: any
dev_dependencies:
  unittest: '>=0.11.0 <0.12.0'
