name: hetimanet
version: 0.0.1
description: A starting point for Dart libraries or applications.
dependencies:
  chrome: any
  hetimacore:
    path: /Users/kiyohiro/dart/git/dart_hetimacore
  hetimafile:
    git: https://github.com/kyorohiro/dart_hetimafile.git
  hetimaregex:
    git: https://github.com/kyorohiro/dart_hetimaregex
  xml: any
dev_dependencies:
  unittest: '>=0.11.0 <0.12.0'
